language: node_js
node_js:
- '8'
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
branches:
  only:
  - "/^v[0-9]/"
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: ovKLFMFUUcYhsVnSgEn9BbdjNa0ZjuyS58BjHLP+LAA7O40XoyM1DrOG6TbJlbLTUzjN2zaGzj7aNy9hHyGD+utycQD++k59gx43DkvY5QhJpx5FEXHCcxN4G2Ja09jfVfWSqMMeVZp8WSPL+c+uKG7GJ6h+X1/Whh5a52+XVbImBnNXGhfuiTYsdMNw3yVdH9awG12+ZHgVrxjW0unCkNN8oYojyZy2nK/M6F8kmK4XmycRvenSVNC0HM4JFEAkd4FrwRZnd/+HDnUW6DfRrIrNqwLmC6QWFZkBeLXpx0n1ml5QndCrICBreje/CsqH27JdRTqJyUSJGe1dE0rb61QsfdDRjR4IK9jCXozyJfXb7x+kNCbvkd+9Lebt8Ydm60IOnyCBPqCFgjdEZCfAB3GXqAd3ma91SFyPJKLlRV9y6SCOwZ6Tj4gDp0KeRrIQsfU1VOI2sFyjPXetJPwCcYvp0HzGOQy6HijB015YIql5eqFl4FNsbv7UY2Jm8dmfVazMKPEvcMW87/dChXpxFXO0E9Qx5SbUMdDmkBH74MDaESoLGmfNfYBcd01Ph5wNTSP2gf7dz/wUC5wtz6Sf1U12r/T8/2mQK8U3J2hfcgCet1cZWyjTe0zdxsW1K8B2uYYfmYaaRl78xfBZATkQU1Fs9VOhvtl2+kdcW/ZfGFI=
  on:
    tags: true
    repo: octoblu/storefront-ica-generator
